version: '3.8'

services:
  backend:
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - '5000:8000'
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - .:/app
      
      - '/home/ichram:/home/ichram'
      - '/home/ichram/fim/incron_status.txt:/app/incron_status.txt'
      - ./db.sqlite3:/app/db.sqlite3

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: monitoring_prometheus
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.retention.time=7d'
  #   ports:
  #     - '127.0.0.1:9090:9090'

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: monitoring_sensor
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: monitoring_dashboard
  #   restart: unless-stopped
  #   ports:
  #     - '127.0.0.1:3000:3000'
  #   volumes:
  #     - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
